/*
 Navicat Premium Data Transfer

 Source Server         : x
 Source Server Type    : MySQL
 Source Server Version : 100121
 Source Host           : phpmyadmin.yousoft.vn:3306
 Source Schema         : iht

 Target Server Type    : MySQL
 Target Server Version : 100121
 File Encoding         : 65001

 Date: 19/06/2019 13:23:03
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for districts
-- ----------------------------
DROP TABLE IF EXISTS `districts`;
CREATE TABLE `districts`  (
  `id` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `type` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `province_id` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `publish` tinyint(1) NOT NULL DEFAULT 0,
  `publish_2` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of districts
-- ----------------------------
INSERT INTO `districts` VALUES ('001', 'Quận Ba Đình', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('002', 'Quận Hoàn Kiếm', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('003', 'Quận Tây Hồ', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('004', 'Quận Long Biên', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('005', 'Quận Cầu Giấy', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('006', 'Quận Đống Đa', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('007', 'Quận Hai Bà Trưng', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('008', 'Quận Hoàng Mai', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('009', 'Quận Thanh Xuân', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('016', 'Huyện Sóc Sơn', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('017', 'Huyện Đông Anh', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('018', 'Huyện Gia Lâm', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('019', 'Quận Nam Từ Liêm', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('020', 'Huyện Thanh Trì', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('021', 'Quận Bắc Từ Liêm', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('024', 'Thành phố Hà Giang', 'Thành phố', '02', 0, 0);
INSERT INTO `districts` VALUES ('026', 'Huyện Đồng Văn', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('027', 'Huyện Mèo Vạc', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('028', 'Huyện Yên Minh', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('029', 'Huyện Quản Bạ', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('030', 'Huyện Vị Xuyên', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('031', 'Huyện Bắc Mê', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('032', 'Huyện Hoàng Su Phì', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('033', 'Huyện Xín Mần', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('034', 'Huyện Bắc Quang', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('035', 'Huyện Quang Bình', 'Huyện', '02', 0, 0);
INSERT INTO `districts` VALUES ('040', 'Thành phố Cao Bằng', 'Thành phố', '04', 0, 0);
INSERT INTO `districts` VALUES ('042', 'Huyện Bảo Lâm', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('043', 'Huyện Bảo Lạc', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('044', 'Huyện Thông Nông', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('045', 'Huyện Hà Quảng', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('046', 'Huyện Trà Lĩnh', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('047', 'Huyện Trùng Khánh', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('048', 'Huyện Hạ Lang', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('049', 'Huyện Quảng Uyên', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('050', 'Huyện Phục Hoà', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('051', 'Huyện Hoà An', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('052', 'Huyện Nguyên Bình', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('053', 'Huyện Thạch An', 'Huyện', '04', 0, 0);
INSERT INTO `districts` VALUES ('058', 'Thành Phố Bắc Kạn', 'Thành phố', '06', 0, 0);
INSERT INTO `districts` VALUES ('060', 'Huyện Pác Nặm', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('061', 'Huyện Ba Bể', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('062', 'Huyện Ngân Sơn', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('063', 'Huyện Bạch Thông', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('064', 'Huyện Chợ Đồn', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('065', 'Huyện Chợ Mới', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('066', 'Huyện Na Rì', 'Huyện', '06', 0, 0);
INSERT INTO `districts` VALUES ('070', 'Thành phố Tuyên Quang', 'Thành phố', '08', 0, 0);
INSERT INTO `districts` VALUES ('071', 'Huyện Lâm Bình', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('072', 'Huyện Nà Hang', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('073', 'Huyện Chiêm Hóa', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('074', 'Huyện Hàm Yên', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('075', 'Huyện Yên Sơn', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('076', 'Huyện Sơn Dương', 'Huyện', '08', 0, 0);
INSERT INTO `districts` VALUES ('080', 'Thành phố Lào Cai', 'Thành phố', '10', 0, 0);
INSERT INTO `districts` VALUES ('082', 'Huyện Bát Xát', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('083', 'Huyện Mường Khương', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('084', 'Huyện Si Ma Cai', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('085', 'Huyện Bắc Hà', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('086', 'Huyện Bảo Thắng', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('087', 'Huyện Bảo Yên', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('088', 'Huyện Sa Pa', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('089', 'Huyện Văn Bàn', 'Huyện', '10', 0, 0);
INSERT INTO `districts` VALUES ('094', 'Thành phố Điện Biên Phủ', 'Thành phố', '11', 0, 0);
INSERT INTO `districts` VALUES ('095', 'Thị Xã Mường Lay', 'Thị xã', '11', 0, 0);
INSERT INTO `districts` VALUES ('096', 'Huyện Mường Nhé', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('097', 'Huyện Mường Chà', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('098', 'Huyện Tủa Chùa', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('099', 'Huyện Tuần Giáo', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('100', 'Huyện Điện Biên', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('101', 'Huyện Điện Biên Đông', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('102', 'Huyện Mường Ảng', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('103', 'Huyện Nậm Pồ', 'Huyện', '11', 0, 0);
INSERT INTO `districts` VALUES ('105', 'Thành phố Lai Châu', 'Thành phố', '12', 0, 0);
INSERT INTO `districts` VALUES ('106', 'Huyện Tam Đường', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('107', 'Huyện Mường Tè', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('108', 'Huyện Sìn Hồ', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('109', 'Huyện Phong Thổ', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('110', 'Huyện Than Uyên', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('111', 'Huyện Tân Uyên', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('112', 'Huyện Nậm Nhùn', 'Huyện', '12', 0, 0);
INSERT INTO `districts` VALUES ('116', 'Thành phố Sơn La', 'Thành phố', '14', 0, 0);
INSERT INTO `districts` VALUES ('118', 'Huyện Quỳnh Nhai', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('119', 'Huyện Thuận Châu', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('120', 'Huyện Mường La', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('121', 'Huyện Bắc Yên', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('122', 'Huyện Phù Yên', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('123', 'Huyện Mộc Châu', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('124', 'Huyện Yên Châu', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('125', 'Huyện Mai Sơn', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('126', 'Huyện Sông Mã', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('127', 'Huyện Sốp Cộp', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('128', 'Huyện Vân Hồ', 'Huyện', '14', 0, 0);
INSERT INTO `districts` VALUES ('132', 'Thành phố Yên Bái', 'Thành phố', '15', 0, 0);
INSERT INTO `districts` VALUES ('133', 'Thị xã Nghĩa Lộ', 'Thị xã', '15', 0, 0);
INSERT INTO `districts` VALUES ('135', 'Huyện Lục Yên', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('136', 'Huyện Văn Yên', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('137', 'Huyện Mù Căng Chải', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('138', 'Huyện Trấn Yên', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('139', 'Huyện Trạm Tấu', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('140', 'Huyện Văn Chấn', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('141', 'Huyện Yên Bình', 'Huyện', '15', 0, 0);
INSERT INTO `districts` VALUES ('148', 'Thành phố Hòa Bình', 'Thành phố', '17', 0, 0);
INSERT INTO `districts` VALUES ('150', 'Huyện Đà Bắc', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('151', 'Huyện Kỳ Sơn', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('152', 'Huyện Lương Sơn', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('153', 'Huyện Kim Bôi', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('154', 'Huyện Cao Phong', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('155', 'Huyện Tân Lạc', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('156', 'Huyện Mai Châu', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('157', 'Huyện Lạc Sơn', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('158', 'Huyện Yên Thủy', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('159', 'Huyện Lạc Thủy', 'Huyện', '17', 0, 0);
INSERT INTO `districts` VALUES ('164', 'Thành phố Thái Nguyên', 'Thành phố', '19', 0, 0);
INSERT INTO `districts` VALUES ('165', 'Thành phố Sông Công', 'Thành phố', '19', 0, 0);
INSERT INTO `districts` VALUES ('167', 'Huyện Định Hóa', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('168', 'Huyện Phú Lương', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('169', 'Huyện Đồng Hỷ', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('170', 'Huyện Võ Nhai', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('171', 'Huyện Đại Từ', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('172', 'Thị xã Phổ Yên', 'Thị xã', '19', 0, 0);
INSERT INTO `districts` VALUES ('173', 'Huyện Phú Bình', 'Huyện', '19', 0, 0);
INSERT INTO `districts` VALUES ('178', 'Thành phố Lạng Sơn', 'Thành phố', '20', 0, 0);
INSERT INTO `districts` VALUES ('180', 'Huyện Tràng Định', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('181', 'Huyện Bình Gia', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('182', 'Huyện Văn Lãng', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('183', 'Huyện Cao Lộc', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('184', 'Huyện Văn Quan', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('185', 'Huyện Bắc Sơn', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('186', 'Huyện Hữu Lũng', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('187', 'Huyện Chi Lăng', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('188', 'Huyện Lộc Bình', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('189', 'Huyện Đình Lập', 'Huyện', '20', 0, 0);
INSERT INTO `districts` VALUES ('193', 'Thành phố Hạ Long', 'Thành phố', '22', 0, 0);
INSERT INTO `districts` VALUES ('194', 'Thành phố Móng Cái', 'Thành phố', '22', 0, 0);
INSERT INTO `districts` VALUES ('195', 'Thành phố Cẩm Phả', 'Thành phố', '22', 0, 0);
INSERT INTO `districts` VALUES ('196', 'Thành phố Uông Bí', 'Thành phố', '22', 0, 0);
INSERT INTO `districts` VALUES ('198', 'Huyện Bình Liêu', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('199', 'Huyện Tiên Yên', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('200', 'Huyện Đầm Hà', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('201', 'Huyện Hải Hà', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('202', 'Huyện Ba Chẽ', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('203', 'Huyện Vân Đồn', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('204', 'Huyện Hoành Bồ', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('205', 'Thị xã Đông Triều', 'Thị xã', '22', 0, 0);
INSERT INTO `districts` VALUES ('206', 'Thị xã Quảng Yên', 'Thị xã', '22', 0, 0);
INSERT INTO `districts` VALUES ('207', 'Huyện Cô Tô', 'Huyện', '22', 0, 0);
INSERT INTO `districts` VALUES ('213', 'Thành phố Bắc Giang', 'Thành phố', '24', 0, 0);
INSERT INTO `districts` VALUES ('215', 'Huyện Yên Thế', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('216', 'Huyện Tân Yên', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('217', 'Huyện Lạng Giang', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('218', 'Huyện Lục Nam', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('219', 'Huyện Lục Ngạn', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('220', 'Huyện Sơn Động', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('221', 'Huyện Yên Dũng', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('222', 'Huyện Việt Yên', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('223', 'Huyện Hiệp Hòa', 'Huyện', '24', 0, 0);
INSERT INTO `districts` VALUES ('227', 'Thành phố Việt Trì', 'Thành phố', '25', 0, 0);
INSERT INTO `districts` VALUES ('228', 'Thị xã Phú Thọ', 'Thị xã', '25', 0, 0);
INSERT INTO `districts` VALUES ('230', 'Huyện Đoan Hùng', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('231', 'Huyện Hạ Hoà', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('232', 'Huyện Thanh Ba', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('233', 'Huyện Phù Ninh', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('234', 'Huyện Yên Lập', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('235', 'Huyện Cẩm Khê', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('236', 'Huyện Tam Nông', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('237', 'Huyện Lâm Thao', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('238', 'Huyện Thanh Sơn', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('239', 'Huyện Thanh Thuỷ', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('240', 'Huyện Tân Sơn', 'Huyện', '25', 0, 0);
INSERT INTO `districts` VALUES ('243', 'Thành phố Vĩnh Yên', 'Thành phố', '26', 0, 0);
INSERT INTO `districts` VALUES ('244', 'Thị xã Phúc Yên', 'Thị xã', '26', 0, 0);
INSERT INTO `districts` VALUES ('246', 'Huyện Lập Thạch', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('247', 'Huyện Tam Dương', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('248', 'Huyện Tam Đảo', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('249', 'Huyện Bình Xuyên', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('250', 'Huyện Mê Linh', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('251', 'Huyện Yên Lạc', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('252', 'Huyện Vĩnh Tường', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('253', 'Huyện Sông Lô', 'Huyện', '26', 0, 0);
INSERT INTO `districts` VALUES ('256', 'Thành phố Bắc Ninh', 'Thành phố', '27', 0, 0);
INSERT INTO `districts` VALUES ('258', 'Huyện Yên Phong', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('259', 'Huyện Quế Võ', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('260', 'Huyện Tiên Du', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('261', 'Thị xã Từ Sơn', 'Thị xã', '27', 0, 0);
INSERT INTO `districts` VALUES ('262', 'Huyện Thuận Thành', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('263', 'Huyện Gia Bình', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('264', 'Huyện Lương Tài', 'Huyện', '27', 0, 0);
INSERT INTO `districts` VALUES ('268', 'Quận Hà Đông', 'Quận', '01', 0, 0);
INSERT INTO `districts` VALUES ('269', 'Thị xã Sơn Tây', 'Thị xã', '01', 0, 0);
INSERT INTO `districts` VALUES ('271', 'Huyện Ba Vì', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('272', 'Huyện Phúc Thọ', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('273', 'Huyện Đan Phượng', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('274', 'Huyện Hoài Đức', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('275', 'Huyện Quốc Oai', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('276', 'Huyện Thạch Thất', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('277', 'Huyện Chương Mỹ', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('278', 'Huyện Thanh Oai', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('279', 'Huyện Thường Tín', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('280', 'Huyện Phú Xuyên', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('281', 'Huyện Ứng Hòa', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('282', 'Huyện Mỹ Đức', 'Huyện', '01', 0, 0);
INSERT INTO `districts` VALUES ('288', 'Thành phố Hải Dương', 'Thành phố', '30', 0, 0);
INSERT INTO `districts` VALUES ('290', 'Thị xã Chí Linh', 'Thị xã', '30', 0, 0);
INSERT INTO `districts` VALUES ('291', 'Huyện Nam Sách', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('292', 'Huyện Kinh Môn', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('293', 'Huyện Kim Thành', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('294', 'Huyện Thanh Hà', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('295', 'Huyện Cẩm Giàng', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('296', 'Huyện Bình Giang', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('297', 'Huyện Gia Lộc', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('298', 'Huyện Tứ Kỳ', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('299', 'Huyện Ninh Giang', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('300', 'Huyện Thanh Miện', 'Huyện', '30', 0, 0);
INSERT INTO `districts` VALUES ('303', 'Quận Hồng Bàng', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('304', 'Quận Ngô Quyền', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('305', 'Quận Lê Chân', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('306', 'Quận Hải An', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('307', 'Quận Kiến An', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('308', 'Quận Đồ Sơn', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('309', 'Quận Dương Kinh', 'Quận', '31', 0, 0);
INSERT INTO `districts` VALUES ('311', 'Huyện Thuỷ Nguyên', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('312', 'Huyện An Dương', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('313', 'Huyện An Lão', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('314', 'Huyện Kiến Thuỵ', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('315', 'Huyện Tiên Lãng', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('316', 'Huyện Vĩnh Bảo', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('317', 'Huyện Cát Hải', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('318', 'Huyện Bạch Long Vĩ', 'Huyện', '31', 0, 0);
INSERT INTO `districts` VALUES ('323', 'Thành phố Hưng Yên', 'Thành phố', '33', 0, 0);
INSERT INTO `districts` VALUES ('325', 'Huyện Văn Lâm', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('326', 'Huyện Văn Giang', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('327', 'Huyện Yên Mỹ', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('328', 'Huyện Mỹ Hào', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('329', 'Huyện Ân Thi', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('330', 'Huyện Khoái Châu', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('331', 'Huyện Kim Động', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('332', 'Huyện Tiên Lữ', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('333', 'Huyện Phù Cừ', 'Huyện', '33', 0, 0);
INSERT INTO `districts` VALUES ('336', 'Thành phố Thái Bình', 'Thành phố', '34', 0, 0);
INSERT INTO `districts` VALUES ('338', 'Huyện Quỳnh Phụ', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('339', 'Huyện Hưng Hà', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('340', 'Huyện Đông Hưng', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('341', 'Huyện Thái Thụy', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('342', 'Huyện Tiền Hải', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('343', 'Huyện Kiến Xương', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('344', 'Huyện Vũ Thư', 'Huyện', '34', 0, 0);
INSERT INTO `districts` VALUES ('347', 'Thành phố Phủ Lý', 'Thành phố', '35', 0, 0);
INSERT INTO `districts` VALUES ('349', 'Huyện Duy Tiên', 'Huyện', '35', 0, 0);
INSERT INTO `districts` VALUES ('350', 'Huyện Kim Bảng', 'Huyện', '35', 0, 0);
INSERT INTO `districts` VALUES ('351', 'Huyện Thanh Liêm', 'Huyện', '35', 0, 0);
INSERT INTO `districts` VALUES ('352', 'Huyện Bình Lục', 'Huyện', '35', 0, 0);
INSERT INTO `districts` VALUES ('353', 'Huyện Lý Nhân', 'Huyện', '35', 0, 0);
INSERT INTO `districts` VALUES ('356', 'Thành phố Nam Định', 'Thành phố', '36', 0, 0);
INSERT INTO `districts` VALUES ('358', 'Huyện Mỹ Lộc', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('359', 'Huyện Vụ Bản', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('360', 'Huyện Ý Yên', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('361', 'Huyện Nghĩa Hưng', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('362', 'Huyện Nam Trực', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('363', 'Huyện Trực Ninh', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('364', 'Huyện Xuân Trường', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('365', 'Huyện Giao Thủy', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('366', 'Huyện Hải Hậu', 'Huyện', '36', 0, 0);
INSERT INTO `districts` VALUES ('369', 'Thành phố Ninh Bình', 'Thành phố', '37', 0, 0);
INSERT INTO `districts` VALUES ('370', 'Thành phố Tam Điệp', 'Thành phố', '37', 0, 0);
INSERT INTO `districts` VALUES ('372', 'Huyện Nho Quan', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('373', 'Huyện Gia Viễn', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('374', 'Huyện Hoa Lư', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('375', 'Huyện Yên Khánh', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('376', 'Huyện Kim Sơn', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('377', 'Huyện Yên Mô', 'Huyện', '37', 0, 0);
INSERT INTO `districts` VALUES ('380', 'Thành phố Thanh Hóa', 'Thành phố', '38', 0, 0);
INSERT INTO `districts` VALUES ('381', 'Thị xã Bỉm Sơn', 'Thị xã', '38', 0, 0);
INSERT INTO `districts` VALUES ('382', 'Thị xã Sầm Sơn', 'Thị xã', '38', 0, 0);
INSERT INTO `districts` VALUES ('384', 'Huyện Mường Lát', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('385', 'Huyện Quan Hóa', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('386', 'Huyện Bá Thước', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('387', 'Huyện Quan Sơn', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('388', 'Huyện Lang Chánh', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('389', 'Huyện Ngọc Lặc', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('390', 'Huyện Cẩm Thủy', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('391', 'Huyện Thạch Thành', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('392', 'Huyện Hà Trung', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('393', 'Huyện Vĩnh Lộc', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('394', 'Huyện Yên Định', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('395', 'Huyện Thọ Xuân', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('396', 'Huyện Thường Xuân', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('397', 'Huyện Triệu Sơn', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('398', 'Huyện Thiệu Hóa', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('399', 'Huyện Hoằng Hóa', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('400', 'Huyện Hậu Lộc', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('401', 'Huyện Nga Sơn', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('402', 'Huyện Như Xuân', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('403', 'Huyện Như Thanh', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('404', 'Huyện Nông Cống', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('405', 'Huyện Đông Sơn', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('406', 'Huyện Quảng Xương', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('407', 'Huyện Tĩnh Gia', 'Huyện', '38', 0, 0);
INSERT INTO `districts` VALUES ('412', 'Thành phố Vinh', 'Thành phố', '40', 0, 0);
INSERT INTO `districts` VALUES ('413', 'Thị xã Cửa Lò', 'Thị xã', '40', 0, 0);
INSERT INTO `districts` VALUES ('414', 'Thị xã Thái Hoà', 'Thị xã', '40', 0, 0);
INSERT INTO `districts` VALUES ('415', 'Huyện Quế Phong', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('416', 'Huyện Quỳ Châu', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('417', 'Huyện Kỳ Sơn', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('418', 'Huyện Tương Dương', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('419', 'Huyện Nghĩa Đàn', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('420', 'Huyện Quỳ Hợp', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('421', 'Huyện Quỳnh Lưu', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('422', 'Huyện Con Cuông', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('423', 'Huyện Tân Kỳ', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('424', 'Huyện Anh Sơn', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('425', 'Huyện Diễn Châu', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('426', 'Huyện Yên Thành', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('427', 'Huyện Đô Lương', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('428', 'Huyện Thanh Chương', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('429', 'Huyện Nghi Lộc', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('430', 'Huyện Nam Đàn', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('431', 'Huyện Hưng Nguyên', 'Huyện', '40', 0, 0);
INSERT INTO `districts` VALUES ('432', 'Thị xã Hoàng Mai', 'Thị xã', '40', 0, 0);
INSERT INTO `districts` VALUES ('436', 'Thành phố Hà Tĩnh', 'Thành phố', '42', 0, 0);
INSERT INTO `districts` VALUES ('437', 'Thị xã Hồng Lĩnh', 'Thị xã', '42', 0, 0);
INSERT INTO `districts` VALUES ('439', 'Huyện Hương Sơn', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('440', 'Huyện Đức Thọ', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('441', 'Huyện Vũ Quang', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('442', 'Huyện Nghi Xuân', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('443', 'Huyện Can Lộc', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('444', 'Huyện Hương Khê', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('445', 'Huyện Thạch Hà', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('446', 'Huyện Cẩm Xuyên', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('447', 'Huyện Kỳ Anh', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('448', 'Huyện Lộc Hà', 'Huyện', '42', 0, 0);
INSERT INTO `districts` VALUES ('449', 'Thị xã Kỳ Anh', 'Thị xã', '42', 0, 0);
INSERT INTO `districts` VALUES ('450', 'Thành Phố Đồng Hới', 'Thành phố', '44', 0, 0);
INSERT INTO `districts` VALUES ('452', 'Huyện Minh Hóa', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('453', 'Huyện Tuyên Hóa', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('454', 'Huyện Quảng Trạch', 'Thị xã', '44', 0, 0);
INSERT INTO `districts` VALUES ('455', 'Huyện Bố Trạch', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('456', 'Huyện Quảng Ninh', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('457', 'Huyện Lệ Thủy', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('458', 'Thị xã Ba Đồn', 'Huyện', '44', 0, 0);
INSERT INTO `districts` VALUES ('461', 'Thành phố Đông Hà', 'Thành phố', '45', 0, 0);
INSERT INTO `districts` VALUES ('462', 'Thị xã Quảng Trị', 'Thị xã', '45', 0, 0);
INSERT INTO `districts` VALUES ('464', 'Huyện Vĩnh Linh', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('465', 'Huyện Hướng Hóa', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('466', 'Huyện Gio Linh', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('467', 'Huyện Đa Krông', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('468', 'Huyện Cam Lộ', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('469', 'Huyện Triệu Phong', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('470', 'Huyện Hải Lăng', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('471', 'Huyện Cồn Cỏ', 'Huyện', '45', 0, 0);
INSERT INTO `districts` VALUES ('474', 'Thành phố Huế', 'Thành phố', '46', 0, 0);
INSERT INTO `districts` VALUES ('476', 'Huyện Phong Điền', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('477', 'Huyện Quảng Điền', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('478', 'Huyện Phú Vang', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('479', 'Thị xã Hương Thủy', 'Thị xã', '46', 0, 0);
INSERT INTO `districts` VALUES ('480', 'Thị xã Hương Trà', 'Thị xã', '46', 0, 0);
INSERT INTO `districts` VALUES ('481', 'Huyện A Lưới', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('482', 'Huyện Phú Lộc', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('483', 'Huyện Nam Đông', 'Huyện', '46', 0, 0);
INSERT INTO `districts` VALUES ('490', 'Quận Liên Chiểu', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('491', 'Quận Thanh Khê', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('492', 'Quận Hải Châu', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('493', 'Quận Sơn Trà', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('494', 'Quận Ngũ Hành Sơn', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('495', 'Quận Cẩm Lệ', 'Quận', '48', 0, 0);
INSERT INTO `districts` VALUES ('497', 'Huyện Hòa Vang', 'Huyện', '48', 0, 0);
INSERT INTO `districts` VALUES ('498', 'Huyện Hoàng Sa', 'Huyện', '48', 0, 0);
INSERT INTO `districts` VALUES ('502', 'Thành phố Tam Kỳ', 'Thành phố', '49', 0, 0);
INSERT INTO `districts` VALUES ('503', 'Thành phố Hội An', 'Thành phố', '49', 0, 0);
INSERT INTO `districts` VALUES ('504', 'Huyện Tây Giang', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('505', 'Huyện Đông Giang', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('506', 'Huyện Đại Lộc', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('507', 'Thị xã Điện Bàn', 'Thị xã', '49', 0, 0);
INSERT INTO `districts` VALUES ('508', 'Huyện Duy Xuyên', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('509', 'Huyện Quế Sơn', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('510', 'Huyện Nam Giang', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('511', 'Huyện Phước Sơn', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('512', 'Huyện Hiệp Đức', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('513', 'Huyện Thăng Bình', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('514', 'Huyện Tiên Phước', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('515', 'Huyện Bắc Trà My', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('516', 'Huyện Nam Trà My', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('517', 'Huyện Núi Thành', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('518', 'Huyện Phú Ninh', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('519', 'Huyện Nông Sơn', 'Huyện', '49', 0, 0);
INSERT INTO `districts` VALUES ('522', 'Thành phố Quảng Ngãi', 'Thành phố', '51', 0, 0);
INSERT INTO `districts` VALUES ('524', 'Huyện Bình Sơn', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('525', 'Huyện Trà Bồng', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('526', 'Huyện Tây Trà', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('527', 'Huyện Sơn Tịnh', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('528', 'Huyện Tư Nghĩa', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('529', 'Huyện Sơn Hà', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('530', 'Huyện Sơn Tây', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('531', 'Huyện Minh Long', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('532', 'Huyện Nghĩa Hành', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('533', 'Huyện Mộ Đức', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('534', 'Huyện Đức Phổ', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('535', 'Huyện Ba Tơ', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('536', 'Huyện Lý Sơn', 'Huyện', '51', 0, 0);
INSERT INTO `districts` VALUES ('540', 'Thành phố Qui Nhơn', 'Thành phố', '52', 0, 0);
INSERT INTO `districts` VALUES ('542', 'Huyện An Lão', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('543', 'Huyện Hoài Nhơn', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('544', 'Huyện Hoài Ân', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('545', 'Huyện Phù Mỹ', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('546', 'Huyện Vĩnh Thạnh', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('547', 'Huyện Tây Sơn', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('548', 'Huyện Phù Cát', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('549', 'Thị xã An Nhơn', 'Thị xã', '52', 0, 0);
INSERT INTO `districts` VALUES ('550', 'Huyện Tuy Phước', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('551', 'Huyện Vân Canh', 'Huyện', '52', 0, 0);
INSERT INTO `districts` VALUES ('555', 'Thành phố Tuy Hoà', 'Thành phố', '54', 0, 0);
INSERT INTO `districts` VALUES ('557', 'Thị xã Sông Cầu', 'Thị xã', '54', 0, 0);
INSERT INTO `districts` VALUES ('558', 'Huyện Đồng Xuân', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('559', 'Huyện Tuy An', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('560', 'Huyện Sơn Hòa', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('561', 'Huyện Sông Hinh', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('562', 'Huyện Tây Hoà', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('563', 'Huyện Phú Hoà', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('564', 'Huyện Đông Hòa', 'Huyện', '54', 0, 0);
INSERT INTO `districts` VALUES ('568', 'Thành phố Nha Trang', 'Thành phố', '56', 0, 0);
INSERT INTO `districts` VALUES ('569', 'Thành phố Cam Ranh', 'Thành phố', '56', 0, 0);
INSERT INTO `districts` VALUES ('570', 'Huyện Cam Lâm', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('571', 'Huyện Vạn Ninh', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('572', 'Thị xã Ninh Hòa', 'Thị xã', '56', 0, 0);
INSERT INTO `districts` VALUES ('573', 'Huyện Khánh Vĩnh', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('574', 'Huyện Diên Khánh', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('575', 'Huyện Khánh Sơn', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('576', 'Huyện Trường Sa', 'Huyện', '56', 0, 0);
INSERT INTO `districts` VALUES ('582', 'Thành phố Phan Rang-Tháp Chàm', 'Thành phố', '58', 0, 0);
INSERT INTO `districts` VALUES ('584', 'Huyện Bác Ái', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('585', 'Huyện Ninh Sơn', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('586', 'Huyện Ninh Hải', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('587', 'Huyện Ninh Phước', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('588', 'Huyện Thuận Bắc', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('589', 'Huyện Thuận Nam', 'Huyện', '58', 0, 0);
INSERT INTO `districts` VALUES ('593', 'Thành phố Phan Thiết', 'Thành phố', '60', 0, 0);
INSERT INTO `districts` VALUES ('594', 'Thị xã La Gi', 'Thị xã', '60', 0, 0);
INSERT INTO `districts` VALUES ('595', 'Huyện Tuy Phong', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('596', 'Huyện Bắc Bình', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('597', 'Huyện Hàm Thuận Bắc', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('598', 'Huyện Hàm Thuận Nam', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('599', 'Huyện Tánh Linh', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('600', 'Huyện Đức Linh', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('601', 'Huyện Hàm Tân', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('602', 'Huyện Phú Quí', 'Huyện', '60', 0, 0);
INSERT INTO `districts` VALUES ('608', 'Thành phố Kon Tum', 'Thành phố', '62', 0, 0);
INSERT INTO `districts` VALUES ('610', 'Huyện Đắk Glei', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('611', 'Huyện Ngọc Hồi', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('612', 'Huyện Đắk Tô', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('613', 'Huyện Kon Plông', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('614', 'Huyện Kon Rẫy', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('615', 'Huyện Đắk Hà', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('616', 'Huyện Sa Thầy', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('617', 'Huyện Tu Mơ Rông', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('618', 'Huyện Ia H\' Drai', 'Huyện', '62', 0, 0);
INSERT INTO `districts` VALUES ('622', 'Thành phố Pleiku', 'Thành phố', '64', 0, 0);
INSERT INTO `districts` VALUES ('623', 'Thị xã An Khê', 'Thị xã', '64', 0, 0);
INSERT INTO `districts` VALUES ('624', 'Thị xã Ayun Pa', 'Thị xã', '64', 0, 0);
INSERT INTO `districts` VALUES ('625', 'Huyện KBang', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('626', 'Huyện Đăk Đoa', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('627', 'Huyện Chư Păh', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('628', 'Huyện Ia Grai', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('629', 'Huyện Mang Yang', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('630', 'Huyện Kông Chro', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('631', 'Huyện Đức Cơ', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('632', 'Huyện Chư Prông', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('633', 'Huyện Chư Sê', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('634', 'Huyện Đăk Pơ', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('635', 'Huyện Ia Pa', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('637', 'Huyện Krông Pa', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('638', 'Huyện Phú Thiện', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('639', 'Huyện Chư Pưh', 'Huyện', '64', 0, 0);
INSERT INTO `districts` VALUES ('643', 'Thành phố Buôn Ma Thuột', 'Thành phố', '66', 0, 0);
INSERT INTO `districts` VALUES ('644', 'Thị Xã Buôn Hồ', 'Thị xã', '66', 0, 0);
INSERT INTO `districts` VALUES ('645', 'Huyện Ea H\'leo', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('646', 'Huyện Ea Súp', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('647', 'Huyện Buôn Đôn', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('648', 'Huyện Cư M\'gar', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('649', 'Huyện Krông Búk', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('650', 'Huyện Krông Năng', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('651', 'Huyện Ea Kar', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('652', 'Huyện M\'Đrắk', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('653', 'Huyện Krông Bông', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('654', 'Huyện Krông Pắc', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('655', 'Huyện Krông A Na', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('656', 'Huyện Lắk', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('657', 'Huyện Cư Kuin', 'Huyện', '66', 0, 0);
INSERT INTO `districts` VALUES ('660', 'Thị xã Gia Nghĩa', 'Thị xã', '67', 0, 0);
INSERT INTO `districts` VALUES ('661', 'Huyện Đăk Glong', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('662', 'Huyện Cư Jút', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('663', 'Huyện Đắk Mil', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('664', 'Huyện Krông Nô', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('665', 'Huyện Đắk Song', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('666', 'Huyện Đắk R\'Lấp', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('667', 'Huyện Tuy Đức', 'Huyện', '67', 0, 0);
INSERT INTO `districts` VALUES ('672', 'Thành phố Đà Lạt', 'Thành phố', '68', 0, 0);
INSERT INTO `districts` VALUES ('673', 'Thành phố Bảo Lộc', 'Thành phố', '68', 0, 0);
INSERT INTO `districts` VALUES ('674', 'Huyện Đam Rông', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('675', 'Huyện Lạc Dương', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('676', 'Huyện Lâm Hà', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('677', 'Huyện Đơn Dương', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('678', 'Huyện Đức Trọng', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('679', 'Huyện Di Linh', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('680', 'Huyện Bảo Lâm', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('681', 'Huyện Đạ Huoai', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('682', 'Huyện Đạ Tẻh', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('683', 'Huyện Cát Tiên', 'Huyện', '68', 0, 0);
INSERT INTO `districts` VALUES ('688', 'Thị xã Phước Long', 'Thị xã', '70', 1, 0);
INSERT INTO `districts` VALUES ('689', 'Thị xã Đồng Xoài', 'Thị xã', '70', 1, 0);
INSERT INTO `districts` VALUES ('690', 'Thị xã Bình Long', 'Thị xã', '70', 1, 0);
INSERT INTO `districts` VALUES ('691', 'Huyện Bù Gia Mập', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('692', 'Huyện Lộc Ninh', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('693', 'Huyện Bù Đốp', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('694', 'Huyện Hớn Quản', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('695', 'Huyện Đồng Phú', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('696', 'Huyện Bù Đăng', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('697', 'Huyện Chơn Thành', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('698', 'Huyện Phú Riềng', 'Huyện', '70', 1, 0);
INSERT INTO `districts` VALUES ('703', 'Thành phố Tây Ninh', 'Thành phố', '72', 1, 0);
INSERT INTO `districts` VALUES ('705', 'Huyện Tân Biên', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('706', 'Huyện Tân Châu', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('707', 'Huyện Dương Minh Châu', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('708', 'Huyện Châu Thành', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('709', 'Huyện Hòa Thành', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('710', 'Huyện Gò Dầu', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('711', 'Huyện Bến Cầu', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('712', 'Huyện Trảng Bàng', 'Huyện', '72', 1, 0);
INSERT INTO `districts` VALUES ('718', 'Thành phố Thủ Dầu Một', 'Thành phố', '74', 1, 0);
INSERT INTO `districts` VALUES ('719', 'Huyện Bàu Bàng', 'Huyện', '74', 1, 0);
INSERT INTO `districts` VALUES ('720', 'Huyện Dầu Tiếng', 'Huyện', '74', 1, 0);
INSERT INTO `districts` VALUES ('721', 'Thị xã Bến Cát', 'Thị xã', '74', 1, 0);
INSERT INTO `districts` VALUES ('722', 'Huyện Phú Giáo', 'Huyện', '74', 1, 0);
INSERT INTO `districts` VALUES ('723', 'Thị xã Tân Uyên', 'Thị xã', '74', 1, 0);
INSERT INTO `districts` VALUES ('724', 'Thị xã Dĩ An', 'Thị xã', '74', 1, 0);
INSERT INTO `districts` VALUES ('725', 'Thị xã Thuận An', 'Thị xã', '74', 1, 0);
INSERT INTO `districts` VALUES ('726', 'Huyện Bắc Tân Uyên', 'Huyện', '74', 1, 0);
INSERT INTO `districts` VALUES ('731', 'Thành phố Biên Hòa', 'Thành phố', '75', 1, 0);
INSERT INTO `districts` VALUES ('732', 'Thị xã Long Khánh', 'Thị xã', '75', 1, 0);
INSERT INTO `districts` VALUES ('734', 'Huyện Tân Phú', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('735', 'Huyện Vĩnh Cửu', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('736', 'Huyện Định Quán', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('737', 'Huyện Trảng Bom', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('738', 'Huyện Thống Nhất', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('739', 'Huyện Cẩm Mỹ', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('740', 'Huyện Long Thành', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('741', 'Huyện Xuân Lộc', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('742', 'Huyện Nhơn Trạch', 'Huyện', '75', 1, 0);
INSERT INTO `districts` VALUES ('747', 'Thành phố Vũng Tàu', 'Thành phố', '77', 0, 0);
INSERT INTO `districts` VALUES ('748', 'Thành phố Bà Rịa', 'Thành phố', '77', 0, 0);
INSERT INTO `districts` VALUES ('750', 'Huyện Châu Đức', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('751', 'Huyện Xuyên Mộc', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('752', 'Huyện Long Điền', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('753', 'Huyện Đất Đỏ', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('754', 'Huyện Tân Thành', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('755', 'Huyện Côn Đảo', 'Huyện', '77', 0, 0);
INSERT INTO `districts` VALUES ('760', 'Quận 1', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('761', 'Quận 12', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('762', 'Quận Thủ Đức', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('763', 'Quận 9', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('764', 'Quận Gò Vấp', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('765', 'Quận Bình Thạnh', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('766', 'Quận Tân Bình', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('767', 'Quận Tân Phú', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('768', 'Quận Phú Nhuận', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('769', 'Quận 2', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('770', 'Quận 3', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('771', 'Quận 10', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('772', 'Quận 11', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('773', 'Quận 4', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('774', 'Quận 5', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('775', 'Quận 6', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('776', 'Quận 8', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('777', 'Quận Bình Tân', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('778', 'Quận 7', 'Quận', '79', 1, 0);
INSERT INTO `districts` VALUES ('783', 'Huyện Củ Chi', 'Huyện', '79', 1, 0);
INSERT INTO `districts` VALUES ('784', 'Huyện Hóc Môn', 'Huyện', '79', 1, 0);
INSERT INTO `districts` VALUES ('785', 'Huyện Bình Chánh', 'Huyện', '79', 1, 0);
INSERT INTO `districts` VALUES ('786', 'Huyện Nhà Bè', 'Huyện', '79', 1, 0);
INSERT INTO `districts` VALUES ('787', 'Huyện Cần Giờ', 'Huyện', '79', 1, 0);
INSERT INTO `districts` VALUES ('794', 'Thành phố Tân An', 'Thành phố', '80', 1, 0);
INSERT INTO `districts` VALUES ('795', 'Thị xã Kiến Tường', 'Thị xã', '80', 1, 0);
INSERT INTO `districts` VALUES ('796', 'Huyện Tân Hưng', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('797', 'Huyện Vĩnh Hưng', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('798', 'Huyện Mộc Hóa', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('799', 'Huyện Tân Thạnh', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('800', 'Huyện Thạnh Hóa', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('801', 'Huyện Đức Huệ', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('802', 'Huyện Đức Hòa', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('803', 'Huyện Bến Lức', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('804', 'Huyện Thủ Thừa', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('805', 'Huyện Tân Trụ', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('806', 'Huyện Cần Đước', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('807', 'Huyện Cần Giuộc', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('808', 'Huyện Châu Thành', 'Huyện', '80', 1, 0);
INSERT INTO `districts` VALUES ('815', 'Thành phố Mỹ Tho', 'Thành phố', '82', 0, 0);
INSERT INTO `districts` VALUES ('816', 'Thị xã Gò Công', 'Thị xã', '82', 0, 0);
INSERT INTO `districts` VALUES ('817', 'Thị xã Cai Lậy', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('818', 'Huyện Tân Phước', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('819', 'Huyện Cái Bè', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('820', 'Huyện Cai Lậy', 'Thị xã', '82', 0, 0);
INSERT INTO `districts` VALUES ('821', 'Huyện Châu Thành', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('822', 'Huyện Chợ Gạo', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('823', 'Huyện Gò Công Tây', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('824', 'Huyện Gò Công Đông', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('825', 'Huyện Tân Phú Đông', 'Huyện', '82', 0, 0);
INSERT INTO `districts` VALUES ('829', 'Thành phố Bến Tre', 'Thành phố', '83', 0, 0);
INSERT INTO `districts` VALUES ('831', 'Huyện Châu Thành', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('832', 'Huyện Chợ Lách', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('833', 'Huyện Mỏ Cày Nam', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('834', 'Huyện Giồng Trôm', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('835', 'Huyện Bình Đại', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('836', 'Huyện Ba Tri', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('837', 'Huyện Thạnh Phú', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('838', 'Huyện Mỏ Cày Bắc', 'Huyện', '83', 0, 0);
INSERT INTO `districts` VALUES ('842', 'Thành phố Trà Vinh', 'Thành phố', '84', 0, 0);
INSERT INTO `districts` VALUES ('844', 'Huyện Càng Long', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('845', 'Huyện Cầu Kè', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('846', 'Huyện Tiểu Cần', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('847', 'Huyện Châu Thành', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('848', 'Huyện Cầu Ngang', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('849', 'Huyện Trà Cú', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('850', 'Huyện Duyên Hải', 'Huyện', '84', 0, 0);
INSERT INTO `districts` VALUES ('851', 'Thị xã Duyên Hải', 'Thị xã', '84', 0, 0);
INSERT INTO `districts` VALUES ('855', 'Thành phố Vĩnh Long', 'Thành phố', '86', 0, 0);
INSERT INTO `districts` VALUES ('857', 'Huyện Long Hồ', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('858', 'Huyện Mang Thít', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('859', 'Huyện  Vũng Liêm', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('860', 'Huyện Tam Bình', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('861', 'Thị xã Bình Minh', 'Thị xã', '86', 0, 0);
INSERT INTO `districts` VALUES ('862', 'Huyện Trà Ôn', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('863', 'Huyện Bình Tân', 'Huyện', '86', 0, 0);
INSERT INTO `districts` VALUES ('866', 'Thành phố Cao Lãnh', 'Thành phố', '87', 0, 0);
INSERT INTO `districts` VALUES ('867', 'Thành phố Sa Đéc', 'Thành phố', '87', 0, 0);
INSERT INTO `districts` VALUES ('868', 'Thị xã Hồng Ngự', 'Thị xã', '87', 0, 0);
INSERT INTO `districts` VALUES ('869', 'Huyện Tân Hồng', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('870', 'Huyện Hồng Ngự', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('871', 'Huyện Tam Nông', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('872', 'Huyện Tháp Mười', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('873', 'Huyện Cao Lãnh', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('874', 'Huyện Thanh Bình', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('875', 'Huyện Lấp Vò', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('876', 'Huyện Lai Vung', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('877', 'Huyện Châu Thành', 'Huyện', '87', 0, 0);
INSERT INTO `districts` VALUES ('883', 'Thành phố Long Xuyên', 'Thành phố', '89', 0, 0);
INSERT INTO `districts` VALUES ('884', 'Thành phố Châu Đốc', 'Thành phố', '89', 0, 0);
INSERT INTO `districts` VALUES ('886', 'Huyện An Phú', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('887', 'Thị xã Tân Châu', 'Thị xã', '89', 0, 0);
INSERT INTO `districts` VALUES ('888', 'Huyện Phú Tân', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('889', 'Huyện Châu Phú', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('890', 'Huyện Tịnh Biên', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('891', 'Huyện Tri Tôn', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('892', 'Huyện Châu Thành', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('893', 'Huyện Chợ Mới', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('894', 'Huyện Thoại Sơn', 'Huyện', '89', 0, 0);
INSERT INTO `districts` VALUES ('899', 'Thành phố Rạch Giá', 'Thành phố', '91', 0, 0);
INSERT INTO `districts` VALUES ('900', 'Thị xã Hà Tiên', 'Thị xã', '91', 0, 0);
INSERT INTO `districts` VALUES ('902', 'Huyện Kiên Lương', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('903', 'Huyện Hòn Đất', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('904', 'Huyện Tân Hiệp', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('905', 'Huyện Châu Thành', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('906', 'Huyện Giồng Riềng', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('907', 'Huyện Gò Quao', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('908', 'Huyện An Biên', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('909', 'Huyện An Minh', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('910', 'Huyện Vĩnh Thuận', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('911', 'Huyện Phú Quốc', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('912', 'Huyện Kiên Hải', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('913', 'Huyện U Minh Thượng', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('914', 'Huyện Giang Thành', 'Huyện', '91', 0, 0);
INSERT INTO `districts` VALUES ('916', 'Quận Ninh Kiều', 'Quận', '92', 0, 0);
INSERT INTO `districts` VALUES ('917', 'Quận Ô Môn', 'Quận', '92', 0, 0);
INSERT INTO `districts` VALUES ('918', 'Quận Bình Thuỷ', 'Quận', '92', 0, 0);
INSERT INTO `districts` VALUES ('919', 'Quận Cái Răng', 'Quận', '92', 0, 0);
INSERT INTO `districts` VALUES ('923', 'Quận Thốt Nốt', 'Quận', '92', 0, 0);
INSERT INTO `districts` VALUES ('924', 'Huyện Vĩnh Thạnh', 'Huyện', '92', 0, 0);
INSERT INTO `districts` VALUES ('925', 'Huyện Cờ Đỏ', 'Huyện', '92', 0, 0);
INSERT INTO `districts` VALUES ('926', 'Huyện Phong Điền', 'Huyện', '92', 0, 0);
INSERT INTO `districts` VALUES ('927', 'Huyện Thới Lai', 'Huyện', '92', 0, 0);
INSERT INTO `districts` VALUES ('930', 'Thành phố Vị Thanh', 'Thành phố', '93', 0, 0);
INSERT INTO `districts` VALUES ('931', 'Thị xã Ngã Bảy', 'Thị xã', '93', 0, 0);
INSERT INTO `districts` VALUES ('932', 'Huyện Châu Thành A', 'Huyện', '93', 0, 0);
INSERT INTO `districts` VALUES ('933', 'Huyện Châu Thành', 'Huyện', '93', 0, 0);
INSERT INTO `districts` VALUES ('934', 'Huyện Phụng Hiệp', 'Huyện', '93', 0, 0);
INSERT INTO `districts` VALUES ('935', 'Huyện Vị Thuỷ', 'Huyện', '93', 0, 0);
INSERT INTO `districts` VALUES ('936', 'Huyện Long Mỹ', 'Huyện', '93', 0, 0);
INSERT INTO `districts` VALUES ('937', 'Thị xã Long Mỹ', 'Thị xã', '93', 0, 0);
INSERT INTO `districts` VALUES ('941', 'Thành phố Sóc Trăng', 'Thành phố', '94', 0, 0);
INSERT INTO `districts` VALUES ('942', 'Huyện Châu Thành', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('943', 'Huyện Kế Sách', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('944', 'Huyện Mỹ Tú', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('945', 'Huyện Cù Lao Dung', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('946', 'Huyện Long Phú', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('947', 'Huyện Mỹ Xuyên', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('948', 'Thị xã Ngã Năm', 'Thị xã', '94', 0, 0);
INSERT INTO `districts` VALUES ('949', 'Huyện Thạnh Trị', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('950', 'Thị xã Vĩnh Châu', 'Thị xã', '94', 0, 0);
INSERT INTO `districts` VALUES ('951', 'Huyện Trần Đề', 'Huyện', '94', 0, 0);
INSERT INTO `districts` VALUES ('954', 'Thành phố Bạc Liêu', 'Thành phố', '95', 0, 0);
INSERT INTO `districts` VALUES ('956', 'Huyện Hồng Dân', 'Huyện', '95', 0, 0);
INSERT INTO `districts` VALUES ('957', 'Huyện Phước Long', 'Huyện', '95', 0, 0);
INSERT INTO `districts` VALUES ('958', 'Huyện Vĩnh Lợi', 'Huyện', '95', 0, 0);
INSERT INTO `districts` VALUES ('959', 'Thị xã Giá Rai', 'Thị xã', '95', 0, 0);
INSERT INTO `districts` VALUES ('960', 'Huyện Đông Hải', 'Huyện', '95', 0, 0);
INSERT INTO `districts` VALUES ('961', 'Huyện Hoà Bình', 'Huyện', '95', 0, 0);
INSERT INTO `districts` VALUES ('964', 'Thành phố Cà Mau', 'Thành phố', '96', 0, 0);
INSERT INTO `districts` VALUES ('966', 'Huyện U Minh', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('967', 'Huyện Thới Bình', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('968', 'Huyện Trần Văn Thời', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('969', 'Huyện Cái Nước', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('970', 'Huyện Đầm Dơi', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('971', 'Huyện Năm Căn', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('972', 'Huyện Phú Tân', 'Huyện', '96', 0, 0);
INSERT INTO `districts` VALUES ('973', 'Huyện Ngọc Hiển', 'Huyện', '96', 0, 0);

SET FOREIGN_KEY_CHECKS = 1;
