<?php

namespace App\Models;

use App\Helpers\Business;
use App\User;
use Illuminate\Database\Eloquent\SoftDeletes;

class Car extends BaseModel
{
    use SoftDeletes;

    protected $fillable = [
        'user_id', 'manufacturer', 'brand', 'weight', 'license_plate', 'owner_id', 'number', 'name', 'type'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne(User::class)->select('name', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function owner()
    {
        return $this->belongsTo(Driver::class, 'owner_id', 'id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updating(function ($car){
            if ($car->type == Business::CAR_TYPE_COMPANY){
                $car->owner_id = null;
            }
        });
    }
}