<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class CollectionOfDebt extends Model
{
    protected $fillable = [
      'name', 'money', 'status', 'user_id', 'employee_id', 'note'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($collectionOfDebt){
            $collectionOfDebt->user_id = request()->user()->id;
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'employee_id');
    }
}
