<?php

namespace App\Models;


use App\Helpers\Business;
use App\User;
use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends BaseModel
{
    use SoftDeletes;

    protected $fillable = [
      'user_id', 'type', 'address', 'phone_company', 'tax_code', 'code', 'pic', 'tax'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function order()
    {
        return $this->hasMany(Order::class, 'user_id', 'id')->select('id', 'code', 'status', 'created_at', 'payment_type', 'total_price');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($customer){
            if ($customer->type == Business::CUSTOMER_TYPE_COMPANY){
                $customer->code = static::generateCode();
            }
        });
    }

    /**
     * @return string
     */
    public static function generateCode()
    {
        $count = Customer::whereNotNull('code')->select(['code'])->count() + 1;
        do{
            $code = sprintf("IHT-KH%s%'.02d", date('Ymd'), $count);
            $count++;
        }while (Customer::where('code', $code)->first());
        return $code;
    }
}
